version: '3.9'

services:
  redis-master:
      image: 'redis:6.2-alpine'
      command: redis-server /usr/local/etc/redis/redis.conf
      ports:
        - '40000:6379'
      volumes:
        - ./master.conf:/usr/local/etc/redis/redis.conf
      networks:
        app_subnet:
          ipv4_address: 192.168.0.40
  redis-slave1:
      image: 'redis:6.2-alpine'
      command: redis-server /usr/local/etc/redis/redis.conf
      ports:
        - '40001:6379'
      volumes:
        - ./slave.conf:/usr/local/etc/redis/redis.conf
      networks:
        app_subnet:
          ipv4_address: 192.168.0.41
  redis-slave2:
      image: 'redis:6.2-alpine'
      command: redis-server /usr/local/etc/redis/redis.conf
      ports:
        - '40002:6379'
      volumes:
        - ./slave.conf:/usr/local/etc/redis/redis.conf
      networks:
        app_subnet:
          ipv4_address: 192.168.0.42
